export type LaunchMarket = {
  slug: string;
  name: string;
  state: string;
  stateName: string;
  zip: string;
  phase: 1 | 2 | 3 | 4;
  phaseLabel: string;
  pitch: string;
  verticals: string[];
};

export const launchMarkets: LaunchMarket[] = [
  {
    slug: "fresno-ca",
    name: "Fresno",
    state: "CA",
    stateName: "California",
    zip: "93721",
    phase: 1,
    phaseLabel: "Launch Market",
    pitch: "SecurityMatch's Central California launch market for commercial, event, construction, patrol and standing-guard demand.",
    verticals: ["Construction", "Commercial Property", "Events", "Mobile Patrol"],
  },
  {
    slug: "bakersfield-ca",
    name: "Bakersfield",
    state: "CA",
    stateName: "California",
    zip: "93301",
    phase: 1,
    phaseLabel: "Launch Market",
    pitch: "A core Central California market focused on industrial, construction, event and commercial security assignments.",
    verticals: ["Construction", "Industrial", "Events", "Commercial"],
  },
  {
    slug: "sacramento-ca",
    name: "Sacramento",
    state: "CA",
    stateName: "California",
    zip: "95814",
    phase: 1,
    phaseLabel: "Launch Market",
    pitch: "A major Northern California marketplace for commercial, multifamily, construction, event and institutional security needs.",
    verticals: ["Commercial", "Multifamily", "Construction", "Events"],
  },
  {
    slug: "dallas-fort-worth-tx",
    name: "Dallas–Fort Worth",
    state: "TX",
    stateName: "Texas",
    zip: "75201",
    phase: 2,
    phaseLabel: "Next Expansion",
    pitch: "SecurityMatch's first major Texas expansion market, built around recurring construction and commercial security opportunities.",
    verticals: ["Construction", "Commercial", "Multifamily", "Logistics"],
  },
  {
    slug: "houston-tx",
    name: "Houston",
    state: "TX",
    stateName: "Texas",
    zip: "77002",
    phase: 2,
    phaseLabel: "Next Expansion",
    pitch: "A high-volume market for industrial, logistics, construction and commercial security providers.",
    verticals: ["Industrial", "Logistics", "Construction", "Commercial"],
  },
  {
    slug: "phoenix-az",
    name: "Phoenix",
    state: "AZ",
    stateName: "Arizona",
    zip: "85004",
    phase: 2,
    phaseLabel: "Next Expansion",
    pitch: "A growth-market expansion focused on construction, property, community and mobile-patrol demand.",
    verticals: ["Construction", "Property", "HOA", "Mobile Patrol"],
  },
  {
    slug: "atlanta-ga",
    name: "Atlanta",
    state: "GA",
    stateName: "Georgia",
    zip: "30303",
    phase: 3,
    phaseLabel: "Growth Market",
    pitch: "A Southeast growth market for events, commercial property, construction and standing-guard services.",
    verticals: ["Events", "Commercial", "Construction", "Standing Guard"],
  },
  {
    slug: "orlando-fl",
    name: "Orlando",
    state: "FL",
    stateName: "Florida",
    zip: "32801",
    phase: 3,
    phaseLabel: "Growth Market",
    pitch: "An event and hospitality-oriented market with strong use cases for flexible and rapid-response security staffing.",
    verticals: ["Events", "Hospitality", "Commercial", "Emergency Coverage"],
  },
  {
    slug: "los-angeles-ca",
    name: "Los Angeles",
    state: "CA",
    stateName: "California",
    zip: "90012",
    phase: 3,
    phaseLabel: "Growth Market",
    pitch: "A large Southern California provider and customer market spanning commercial, construction, event and executive-security demand.",
    verticals: ["Commercial", "Construction", "Events", "Executive Protection"],
  },
  {
    slug: "inland-empire-ca",
    name: "Inland Empire",
    state: "CA",
    stateName: "California",
    zip: "92501",
    phase: 3,
    phaseLabel: "Growth Market",
    pitch: "A Southern California logistics, warehouse and construction corridor suited to recurring security assignments.",
    verticals: ["Logistics", "Warehousing", "Construction", "Mobile Patrol"],
  },
  {
    slug: "miami-fl",
    name: "Miami",
    state: "FL",
    stateName: "Florida",
    zip: "33131",
    phase: 4,
    phaseLabel: "Planned Market",
    pitch: "A planned hospitality, event, residential and executive-protection expansion market.",
    verticals: ["Hospitality", "Events", "Residential", "Executive Protection"],
  },
  {
    slug: "tampa-fl",
    name: "Tampa",
    state: "FL",
    stateName: "Florida",
    zip: "33602",
    phase: 4,
    phaseLabel: "Planned Market",
    pitch: "A planned Florida expansion market for commercial, construction and event coverage.",
    verticals: ["Commercial", "Construction", "Events", "Patrol"],
  },
  {
    slug: "charlotte-nc",
    name: "Charlotte",
    state: "NC",
    stateName: "North Carolina",
    zip: "28202",
    phase: 4,
    phaseLabel: "Planned Market",
    pitch: "A planned growth-market launch for commercial, construction and multifamily security needs.",
    verticals: ["Commercial", "Construction", "Multifamily", "Standing Guard"],
  },
  {
    slug: "raleigh-nc",
    name: "Raleigh",
    state: "NC",
    stateName: "North Carolina",
    zip: "27601",
    phase: 4,
    phaseLabel: "Planned Market",
    pitch: "A planned Carolinas market centered on construction, commercial property and campus-adjacent demand.",
    verticals: ["Construction", "Commercial", "Property", "Campus"],
  },
  {
    slug: "las-vegas-nv",
    name: "Las Vegas",
    state: "NV",
    stateName: "Nevada",
    zip: "89101",
    phase: 4,
    phaseLabel: "Planned Market",
    pitch: "A specialized event, convention and executive-protection marketplace.",
    verticals: ["Events", "Conventions", "Executive Protection", "Hospitality"],
  },
  {
    slug: "austin-tx",
    name: "Austin",
    state: "TX",
    stateName: "Texas",
    zip: "78701",
    phase: 4,
    phaseLabel: "Planned Market",
    pitch: "A planned Texas network extension for technology, events, construction and commercial security.",
    verticals: ["Technology", "Events", "Construction", "Commercial"],
  },
  {
    slug: "san-antonio-tx",
    name: "San Antonio",
    state: "TX",
    stateName: "Texas",
    zip: "78205",
    phase: 4,
    phaseLabel: "Planned Market",
    pitch: "A planned Texas expansion for commercial, hospitality, construction and event coverage.",
    verticals: ["Commercial", "Hospitality", "Construction", "Events"],
  },
];

export function marketBySlug(slug: string) {
  return launchMarkets.find((market) => market.slug === slug);
}
